#!/usr/bin/env python3
"""Render the JSON schemas as Markdown reference pages for the Sphinx docs.

Two pages are generated from the committed schemas:

* ``docs/schemas/venues.md`` from ``paperpush/venues.schema.json`` -- the
  shape of a ``venues.json`` entry: venue-level keys, the field definition,
  and the conditional-limit object.
* ``docs/schemas/manuscript_requirements.md`` from
  ``paperpush/manuscript_requirements.schema.json`` -- the shape of a
  ``manuscript_requirements.json`` entry and each of its sections.

Each object becomes one table (key, type, description) so the reference reads
like documentation rather than raw JSON Schema. The schemas themselves are
generated from the dataclasses by ``scripts/gen_venues_schema.py``; run that
first, then this:

    python scripts/gen_schema_docs.py        # rewrite the pages in place
    python scripts/gen_schema_docs.py --check # exit 1 if a page is out of date

The ``--check`` form is what CI runs.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs" / "schemas"

VENUES_SCHEMA = REPO_ROOT / "paperpush" / "venues.schema.json"
REQUIREMENTS_SCHEMA = REPO_ROOT / "paperpush" / "manuscript_requirements.schema.json"

HEADER = "<!-- Generated by scripts/gen_schema_docs.py from {source}; do not edit by hand. -->"


# --- type rendering --------------------------------------------------------


def _anchor(name: str) -> str:
    """The MyST heading anchor for a ``$defs`` entry (see ``_heading``).

    Mirrors MyST's GitHub-style slugs (``myst_heading_anchors``): lower-case,
    spaces to hyphens, underscores kept (``title_page`` -> ``#title_page``).
    """
    return re.sub(r"[^\w\- ]", "", name.lower()).replace(" ", "-")


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def render_type(prop: dict[str, Any]) -> str:
    """A short, human-readable type for one property schema.

    ``anyOf [X, null]`` renders as ``X or null``; an ``enum`` lists its values;
    an array names its item type; a ``$ref`` becomes a link to that object's
    table on the same page.
    """
    if "$ref" in prop:
        name = _ref_name(prop["$ref"])
        return f"[{name}](#{_anchor(name)})"
    if "anyOf" in prop:
        options = [render_type(p) for p in prop["anyOf"]]
        nulls = [o for o in options if o == "null"]
        others = [o for o in options if o != "null"]
        joined = " or ".join(others) if others else "any"
        return f"{joined} or null" if nulls else joined
    if "enum" in prop:
        return " \\| ".join(f"`{v}`" for v in prop["enum"])
    if "const" in prop:
        return f"`{prop['const']}`"
    kind = prop.get("type")
    if kind == "array":
        items = prop.get("items")
        return f"list of {render_type(items)}" if items else "list"
    if kind == "object":
        extra = prop.get("additionalProperties")
        if isinstance(extra, dict) and extra:
            return f"map of {render_type(extra)}"
        return "object"
    if isinstance(kind, list):
        return " or ".join(kind)
    if kind:
        return str(kind)
    if prop == {} or prop is False:
        return "any" if prop == {} else "not allowed"
    return "any"


def _cell(text: str) -> str:
    """Escape a description for a Markdown table cell."""
    return " ".join(text.split()).replace("|", "\\|")


def render_table(schema: dict[str, Any]) -> list[str]:
    """One Markdown table for an object schema's ``properties``."""
    required = set(schema.get("required", []))
    lines = ["| Key | Type | Description |", "|---|---|---|"]
    for name, prop in schema.get("properties", {}).items():
        label = f"`{name}`" + (" (required)" if name in required else "")
        description = prop.get("description", "")
        if not description and "anyOf" in prop:
            description = next((p.get("description", "") for p in prop["anyOf"] if p.get("description")), "")
        lines.append(f"| {label} | {render_type(prop)} | {_cell(description)} |")
    return lines


def _heading(level: int, name: str) -> list[str]:
    return [f"{'#' * level} {name}", ""]


# --- pages -----------------------------------------------------------------


def render_venues_page() -> str:
    schema = json.loads(VENUES_SCHEMA.read_text(encoding="utf-8"))
    defs = schema["$defs"]
    # The field table below documents both the full definition and the
    # inheriting override, so point the `fields` list at that one table.
    defs["venueCommon"]["properties"]["fields"] = {"type": "array", "items": {"$ref": "#/$defs/field"}, "description": "The fields this venue asks for during submission (see the field table)."}
    out = [
        HEADER.format(source="paperpush/venues.schema.json"),
        "",
        "# venues.json reference",
        "",
        "`paperpush/venues.json` describes each venue's **submission form**: the fields the",
        "portal asks for and the constraints on each. The top-level object maps a venue",
        "slug (`biorxiv`, `nature`, ...) to a venue entry. This page is generated from",
        "`paperpush/venues.schema.json`, which is itself generated from the `Venue` and",
        "`Field` dataclasses in `paperpush/database.py` -- those are the source of truth.",
        "",
        "A venue entry either stands alone or **inherits** another venue's entry. An",
        'inheriting entry (`"inherits": "<slug>"`) takes the base venue\'s keys and',
        "fields wholesale, then overrides individual top-level keys, modifies or adds",
        "fields by `id` (restating only the keys that change; a key set to `null` drops",
        "the inherited value), and drops fields listed in `removed_fields`.",
        "",
    ]
    out += _heading(2, "Venue entry")
    out += ["The keys of one venue entry (the value under a slug).", ""]
    out += render_table(defs["venueCommon"])
    out += [""]
    out += _heading(2, "field")
    out += [
        "One entry of a venue's `fields` list: a value the portal asks for. In a",
        "standalone venue every field is a full definition (`id`, `label`, and `type`",
        "required). In an inheriting venue a field entry is an override: only `id` is",
        "required, every other key is optional, and `null` deletes the inherited key.",
        "",
    ]
    out += render_table(defs["field"])
    out += [""]
    for name, definition in defs.items():
        if name in ("field", "fieldOverride", "venueCommon", "venue"):
            continue
        out += _heading(2, name)
        if definition.get("description"):
            out += [definition["description"], ""]
        out += render_table(definition)
        out += [""]
    return "\n".join(out).rstrip() + "\n"


def render_requirements_page() -> str:
    schema = json.loads(REQUIREMENTS_SCHEMA.read_text(encoding="utf-8"))
    defs = schema["$defs"]
    out = [
        HEADER.format(source="paperpush/manuscript_requirements.schema.json"),
        "",
        "# manuscript_requirements.json reference",
        "",
        "`paperpush/manuscript_requirements.json` records what each venue's **author",
        "guidelines** require of the manuscript itself -- the companion to",
        "`venues.json`, which describes the submission form. `paperpush validate`",
        "measures the uploaded files against these rules and `paperpush requirements",
        "VENUE` prints them. The top-level object maps a venue slug to a venue entry;",
        "the special keys `$schema` and `$aliases` are metadata (see below). This page",
        "is generated from `paperpush/manuscript_requirements.schema.json`, which is",
        "itself generated from the dataclasses in `paperpush/requirements.py`.",
        "",
        "Every key is optional: an entry records only what the guidelines state, and",
        "rules with no structured key go in a section's `notes` list. Two mechanisms",
        "keep entries short: `inherits` starts from another venue's entry and overrides",
        "keys section by section (a key set to `null` drops the inherited value;",
        "`notes` accumulate), and `article_types` holds per-article-type overrides",
        "keyed by the exact option string of the field named in `article_type_field`.",
        "",
    ]
    out += _heading(2, "Venue entry")
    out += ["The keys of one venue entry. Each section key holds the object described in its own table below.", ""]
    out += render_table(defs["venue"])
    out += [""]
    out += _heading(2, "rules")
    out += [defs["rules"].get("description", ""), "", "The same section keys as a venue entry (plus `notes`); used as the value of each `article_types` entry.", ""]
    for name, definition in defs.items():
        if name in ("venue", "rules"):
            continue
        out += _heading(2, name)
        out += render_table(definition)
        out += [""]
    out += _heading(2, "$aliases")
    aliases = schema["properties"]["$aliases"]
    out += [aliases.get("description", ""), ""]
    out += render_table(aliases)
    return "\n".join(out).rstrip() + "\n"


PAGES = (
    (DOCS_DIR / "venues.md", render_venues_page),
    (DOCS_DIR / "manuscript_requirements.md", render_requirements_page),
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit non-zero if a page is out of date instead of rewriting it")
    args = parser.parse_args()

    status = 0
    for path, render in PAGES:
        updated = render()
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        rel = path.relative_to(REPO_ROOT)
        if args.check:
            if current != updated:
                print(f"{rel} is out of date. Run: python scripts/gen_schema_docs.py", file=sys.stderr)
                status = 1
            continue
        if current != updated:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(updated, encoding="utf-8")
            print(f"Updated {rel}")
        else:
            print(f"{rel} already up to date")
    return status


if __name__ == "__main__":
    raise SystemExit(main())
