#!/usr/bin/env python3
"""Copy the agent-facing docs into the package so they ship with the wheel.

``AGENTS.md`` lives at the repo root because that is where agent tooling looks
for it, but a pip install only gets what is inside ``paperpush/``. An agent
helping someone who ran ``pip install paperpush`` therefore has no way to read
the submission contract -- it is in the repo it does not have. Mirroring the
file into ``paperpush/_docs/`` (shipped via ``[tool.setuptools.package-data]``)
makes it readable offline through ``paperpush --agent-guide``, with no network
access and no version skew against whatever ``main`` says today.

The root copy stays canonical; this script only ever writes the package copy:

    python scripts/sync_agent_docs.py          # copy in place
    python scripts/sync_agent_docs.py --check  # exit 1 if the copy is stale

The ``--check`` form is suitable for CI or a pre-commit hook.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_DOCS_DIR = REPO_ROOT / "paperpush" / "_docs"

# (source at the repo root, destination basename inside paperpush/_docs).
# Lowercase destinations because these are package data, not the root-level
# convention files agent tooling scans for by name.
DOCS = [("AGENTS.md", "agents.md")]

HEADER = "<!-- Generated by scripts/sync_agent_docs.py -- do not edit.\n" "     Edit {source} at the repo root instead. -->\n\n"


def _expected(source: Path, source_name: str) -> str:
    return HEADER.format(source=source_name) + source.read_text(encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if a package copy is missing or out of date, without writing",
    )
    args = parser.parse_args(argv)

    PACKAGE_DOCS_DIR.mkdir(parents=True, exist_ok=True)

    stale: list[str] = []
    written: list[str] = []

    for source_name, dest_name in DOCS:
        source = REPO_ROOT / source_name
        if not source.is_file():
            print(f"error: missing source doc {source_name}", file=sys.stderr)
            return 1

        dest = PACKAGE_DOCS_DIR / dest_name
        expected = _expected(source, source_name)
        current = dest.read_text(encoding="utf-8") if dest.is_file() else None

        if current == expected:
            continue

        if args.check:
            stale.append(f"{source_name} -> paperpush/_docs/{dest_name}")
        else:
            dest.write_text(expected, encoding="utf-8")
            written.append(f"paperpush/_docs/{dest_name}")

    if stale:
        print("Package doc copies are out of date:", file=sys.stderr)
        for entry in stale:
            print(f"  {entry}", file=sys.stderr)
        print("Run: python scripts/sync_agent_docs.py", file=sys.stderr)
        return 1

    for entry in written:
        print(f"wrote {entry}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
